version: "3.9"
services:
  mongo4:
    image: mongo:4.4.5-bionic
    container_name: mongodb-4.4.5
    restart: always
    ports:
      - 27017:27017
    volumes:
      - D:/docker-volumes/mongodb-4x/data-db:/data/db
      - ./initdb/:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      # This variable allows you to specify the name of a database to be used for creation
      # scripts in /docker-entrypoint-initdb.d/*.js (see Initializing a fresh instance below).
      # MongoDB is fundamentally designed for "create on first use",
      # so if you do not insert data with your JavaScript files, then no database is created.
      MONGO_INITDB_DATABASE: dev_vergilyn