spring:
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      # hibernate.ejb.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
