logging:
  level:
    com.vergilyn.examples.mybatis.cache.mapper: TRACE
    org.mybatis.spring.transaction: DEBUG

mybatis:
#  config-location: mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
    # 开启二级缓存
    cache-enabled: true