spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      username: root
      password: '123456' # 必须加单引号，否则被认为是NULL
      authentication-database: admin
      database: dev_vergilyn
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
