logging:
  level:
    com.vergilyn.examples.mybatis.plus.mapper: TRACE

mybatis:
  #  config-location: mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler